name = "astraea-cli"
account_id = "your_cloudflare_account_id" 
route = "your-domain.com/*"  # Or a subdomain like cli.your-domain.com

[build]
  command = "npm run build" 

[[r2_buckets]]
  binding = "ASTRAEA_DATA" # Use the same name as in your code
  bucket_name = "astraea-cli-data" 

[vars]
  OPENAI_API_KEY = "your_openai_api_key" # This is just an example, use secrets!

# ... other configurations ...
